name: Integration Test

on:
  # push:
    # branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: alonza0314/free-ran-ue
  IMAGE_TAG: latest
  COMPOSE_REPO_URL: https://github.com/free-ran-ue/fru-compose.git
  COMPOSE_REPO_NAME: fru-compose
  SOURCE_REPO_NAME: free-ran-ue

jobs:
  integration-test:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check commands
        run: |
          docker --version
          curl --version
          jq --version

      - name: Build free-ran-ue image
        run: |
          cd $GITHUB_WORKSPACE/..
          git clone $COMPOSE_REPO_URL
          cp -r $GITHUB_WORKSPACE $COMPOSE_REPO_NAME/$SOURCE_REPO_NAME
          cd $COMPOSE_REPO_NAME
          make

      - name: Test free-ran-ue image
        run: |
          docker images
          docker run --rm $IMAGE_NAME:$IMAGE_TAG ls /$SOURCE_REPO_NAME/free-ran-ue
          docker run --rm $IMAGE_NAME:$IMAGE_TAG ls /$SOURCE_REPO_NAME/console

      - name: Run test basic
        run: ./script/integration-test-script/integration-test.sh basic

      - name: Run test dc-static
        run: ./script/integration-test-script/integration-test.sh dc-static

      - name: Run test dc-dynamic
        run: ./script/integration-test-script/integration-test.sh dc-dynamic

      - name: Run test ulcl
        run: ./script/integration-test-script/integration-test.sh ulcl

      - name: Clean up docker resources
        if: always()
        run: docker system prune -a -f --volumes
