name: Integration Test

on:
  # push:
    # branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  COMPOSE_REPO_URL: https://github.com/free-ran-ue/fru-compose.git
  COMPOSE_REPO_NAME: fru-compose
  SOURCE_REPO_URL: https://github.com/${{ github.repository }}.git
  SOURCE_REPO_NAME: free-ran-ue
  IMAGE_NAME: alonza0314/free-ran-ue
  IMAGE_TAG: test

jobs:
  integration-test:
    runs-on: self-hosted

    steps:
      - name: Check commands
        run: |
          docker --version
          curl --version
          jq --version

      - name: Clone fru-compose and fetch PR
        run: |
          rm -rf $COMPOSE_REPO_NAME
          git clone $COMPOSE_REPO_URL $COMPOSE_REPO_NAME
          cd $COMPOSE_REPO_NAME
          git clone $SOURCE_REPO_URL $SOURCE_REPO_NAME
          cd $SOURCE_REPO_NAME
          git fetch origin +${{ github.ref }}:refs/remotes/origin/pr
          git checkout origin/pr

      - name: Build free-ran-ue image
        run: |
          cd $COMPOSE_REPO_NAME
          make integration-test

      - name: Test free-ran-ue image
        run: |
          docker images
          docker run --rm $IMAGE_NAME:$IMAGE_TAG ls /$SOURCE_REPO_NAME/free-ran-ue
          docker run --rm $IMAGE_NAME:$IMAGE_TAG ls /$SOURCE_REPO_NAME/console

      - name: Run test basic
        run: |
          cd $COMPOSE_REPO_NAME
          ./script/integration-test-script/integration-test.sh basic

      - name: Run test dc-static
        run: 
          cd $COMPOSE_REPO_NAME
          ./script/integration-test-script/integration-test.sh dc-static

      - name: Run test dc-dynamic
        run: |
          cd $COMPOSE_REPO_NAME
          ./script/integration-test-script/integration-test.sh dc-dynamic

      - name: Run test ulcl
        run: |
          cd $COMPOSE_REPO_NAME
          ./script/integration-test-script/integration-test.sh ulcl

      - name: Clean up docker resources
        if: always()
        run: |
          cd ..
          rm -rf $COMPOSE_REPO_NAME
          docker system prune -a -f --volumes
